---
- hosts: all
  become: yes
  tasks:
  - name: update
    apt:
     update_cache: true
  - name: nginx
    apt: pkg=nginx state=present     
  - name: Apache
    apt:
     name: apache2
     state: present
  - name: apache2 listen on port 80
    lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 8081" line="Listen 80" state=present
    notify:
       - restart apache2

  - name: apache2 virtualhost on port 80
    lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:8081>" line="<VirtualHost *:80>" state=present
    notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
